export const CLIENT_ID = 'WebSettings';
export const CLIENT_TYPE = '1';
export const APP_VERSION = '1.0.0';
export const API_URL = 'https://dev.protonmail.com/api';
export const API_VERSION = '3';
export const DATE_VERSION = 'Fri, 31 May 2019 06:33:11 GMT';
export const CHANGELOG_PATH = 'assets/changelog.tpl.html';
export const VERSION_PATH = 'assets/version.json';
export const TRANSLATIONS = [];
